public final class ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310 extends java.lang.Object implements org.junit.jupiter.api.function.Executable
{
    sortpom.exception.FailureException cap0;

    public static org.junit.jupiter.api.function.Executable bootstrap$(sortpom.exception.FailureException)
    {
        sortpom.exception.FailureException $r0;
        ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310 $r1;

        $r0 := @parameter0: sortpom.exception.FailureException;

        $r1 = new ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310;

        specialinvoke $r1.<ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310: void <init>(sortpom.exception.FailureException)>($r0);

        return $r1;
    }

    public void <init>(sortpom.exception.FailureException)
    {
        ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310 $r0;
        sortpom.exception.FailureException $r1;

        $r0 := @this: ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310;

        $r1 := @parameter0: sortpom.exception.FailureException;

        specialinvoke $r0.<java.lang.Object: void <init>()>();

        $r0.<ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310: sortpom.exception.FailureException cap0> = $r1;

        return;
    }

    public void execute()
    {
        ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310 $r0;
        sortpom.exception.FailureException $r1;

        $r0 := @this: ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310;

        $r1 = $r0.<ExceptionConverterTest$lambda_failureExceptionShouldThrowMojoFailureException_2__310: sortpom.exception.FailureException cap0>;

        staticinvoke <sortpom.exception.ExceptionConverterTest: void lambda$failureExceptionShouldThrowMojoFailureException$2(sortpom.exception.FailureException)>($r1);

        return;
    }
}
